TILE_SIZE = 64
WINDOW_WIDTH = 960
WINDOW_HEIGHT = 960

WIDTH = int(WINDOW_WIDTH / TILE_SIZE)
HEIGHT = int(WINDOW_HEIGHT / TILE_SIZE)

LABEL_COLOR = (100, 255, 100, 255)
PRESS_LABEL_COLOR = (255, 222, 20, 255)

LABEL_X = WINDOW_WIDTH // 7 + TILE_SIZE * 4
LABEL_PRESS_X = WINDOW_WIDTH // 7

LABEL_Y = (WINDOW_HEIGHT // 5) * 4 - TILE_SIZE
LABEL1_Y = (WINDOW_HEIGHT // 5) * 3
LABEL2_Y = (WINDOW_HEIGHT // 5) * 2 + TILE_SIZE

MAIN_LABEL_X = WINDOW_WIDTH // 2

MAIN_LABEL_Y = (WINDOW_HEIGHT // 5) * 3 - TILE_SIZE
MAIN_LABEL1_Y = (WINDOW_HEIGHT // 5) * 2

FONT_SIZE = 36

SNAKE_IMAGE_X = 5 * TILE_SIZE
SNAKE_IMAGE_Y = 9 * TILE_SIZE

SNAKE_IMAGE_WIDTH = TILE_SIZE * 5
SNAKE_IMAGE_HEIGHT = TILE_SIZE * 5

SCORE_FONT_SIZE = 42
TIME_TO_MOVE = 1/6

SIDE_PENALTY = 20
NEXT_SIDE_PENALTY = 5

A_STAR, DIJKSTRA, GREEDY_SEARCH = (0, 1, 2)
ALGORITHM = A_STAR

MAX_TRIES_FIND_SPACE = WIDTH * HEIGHT
MAX_TRIES_FIND_SPACE_NOT_SIDE = 10
MAX_TRIES_FIND_PATH = 10
